local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/img/uploads" # Media files will be stored in the repo under src/img/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /img/uploads

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "src/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project Provocation", name: "projprov", widget: "string"}
      - label: "Chips"
        name: "chip"
        widget: "list"
        fields:
          - {label: "chips", name: "chips", widget: "string"}
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        fields:
          - {label: "Ingredients", name: "ingredients", widget: "string"}
      - {label: "Featured Image", name: "featimg", widget: "image"}
      - {label: "Client", name: "client", widget: "string"}
      - label: "Delivery"
        name: "delivery"
        widget: "list"
        fields:
          - {label: "Delivery", name: "delivery", widget: "string"}
      - label: "Collaborators"
        name: "collaborators"
        widget: "list"
        fields:
          - {label: "Collaborators", name: "collaborators", widget: "string"}
      - {label: "Project Context", name: "projctx", widget: "string"}
      - label: "Project images"
        name: "projimg"
        widget: "list"
        fields:
          - {label: "project images", name: "projimg", widget: "image", required: false, hint: "Image should be 16:9"}
          - {label: "project caption", name: "caption", widget: "string", required: false, hint: "Image should be 16:9"}
      - label: "Project videos"
        name: "project videos"
        widget: "list"
        fields:
          - {label: "project videos", name: "project_videos", widget: "string", required: false, hint: "add video links"}
      - {label: "Related Project", name: "relprojname", widget: "string"}
      - {label: "Related Project Provocation", name: "relprojprov", widget: "string"}
      - {label: "Related Project Link", name: "relprojlink", widget: "string"}
      - {label: "Related Project Image", name: "relprojimg", widget: "image", required: false}
      - {label: "Project Detail", name: "body", widget: "markdown"}