local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/img/uploads" # Media files will be stored in the repo under src/img/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /img/uploads

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "src/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featimg", widget: "image" }
      - label: "Collaborators"
        name: "collaborators"
        widget: "list"
        collapsed: false
        fields:
          - { label: "Collaborators", name: "collaborators", widget: "string" }
      - label: "Project images"
        name: "projimg"
        widget: "list"
        fields:
          - {
              label: "project images",
              name: "img",
              widget: "image",
              required: false,
              hint: "Image should be 16:9",
            }
          - {
              label: "project caption",
              name: "caption",
              widget: "string",
              required: false,
              hint: "Image should be 16:9",
            }
      - {
          label: "project videos",
          name: "project_videos",
          widget: "string",
          required: false,
          default: "none",
          hint: "add video links, replace the word watch in the youtube link with embed in the same hyperlink. If there is no video link please use the words 'none' leaving it blank will break the page",
        }
      - { label: "Project Detail", name: "body", widget: "markdown" }
